import { Work_Sans } from "next/font/google";
import "./globals.css";
import 'easymde/dist/easymde.min.css'; // Import EasyMDE CSS   

// Load Work Sans from Google Fonts
const workSans = Work_Sans({
  weight: ['100', '200', '400', '500', '600', '700', '800', '900'],  // choose weights you need
  subsets: ['latin'],  // or ['latin-ext'] if needed
  variable: '--font-work-sans',  // Custom CSS variable name
  display: 'swap',  // Ensures text is visible during font load
});

export const metadata = {
  title: "Startup Directory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={workSans.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
